source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!


target 'KlaviyoSwift_Example' do
  pod "KlaviyoSwift", :path => '../'
end

target 'KlaviyoSwift_Tests' do
  pod "KlaviyoSwift", :path => '../'
end
