source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'KlaviyoSwift_Example', :exclusive => true do
  pod "KlaviyoSwift", :path => "../"
end

target 'KlaviyoSwift_Tests', :exclusive => true do
  pod "KlaviyoSwift", :path => "../"

  
end
