exclude: Tests/KlaviyoSwiftTests/__Snapshots__
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/realm/SwiftLint
    rev: 0.53.0
    hooks:
    -   id: swiftlint
        entry: swiftlint --fix --strict
-   repo: https://github.com/nicklockwood/SwiftFormat
    rev: 0.51.2
    hooks:
    -   id: swiftformat
        entry: swiftformat
