# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c  

before_install:
  - gem install bundler -v '= 2.0.1'
install:
- "echo 'gem: --no-rdoc --no-ri --no-document' > ~/.gemrc"
- bundle install
script:
- xcodebuild -workspace KlaviyoSwift.xcworkspace -scheme Example -sdk iphonesimulator
- xcodebuild test -workspace KlaviyoSwift.xcworkspace -scheme KlaviyoSwift -destination "platform=iOS Simulator,OS=12.1,name=iPhone 8" | bundle exec xcpretty -f `xcpretty-travis-formatter`
- bundle exec pod lib lint
osx_image: xcode10.2
xcode_workspace: Example/KlaviyoSwift.xcworkspace
xcode_scheme: Example/KlaviyoSwift
