# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c  

install:
- "echo 'gem: --no-rdoc --no-ri --no-document' > ~/.gemrc"
- gem install xcpretty --quiet
- gem install xcpretty-travis-formatter
script:
- xcodebuild -workspace KlaviyoSwift.xcworkspace -scheme Example -sdk iphonesimulator
- xcodebuild test -workspace KlaviyoSwift.xcworkspace -scheme KlaviyoSwift -destination "platform=iOS Simulator,OS=12.1,name=iPhone 8" | xcpretty -f `xcpretty-travis-formatter`
- pod lib lint
osx_image: xcode10.2
xcode_workspace: Example/KlaviyoSwift.xcworkspace
xcode_scheme: Example/KlaviyoSwift
