name: Bug Report
description: Something isn't working as expected
labels: [bug]
body:
- type: markdown
  attributes:
    value: |
        Thank you for contributing to the Klaviyo Swift SDK!

        Before you submit your issue, please read our [contributing guidelines](https://github.com/klaviyo/klaviyo-swift-sdk/blob/master/.github/CONTRIBUTING.md)
        and answer each question with as much detail as you can.

        > Note: incomplete issues may be de-prioritized or closed.

        We welcome your input! If you have any code suggestions regarding your issue, feel free to
        [submit a pull request](https://github.com/klaviyo/klaviyo-swift-sdk/pulls) after creating an issue.
- type: checkboxes
  attributes:
    label: Checklist
    options:
    - label: I have read the [contributing guidelines](https://github.com/klaviyo/klaviyo-swift-sdk/blob/master/.github/CONTRIBUTING.md)
      required: true
    - label: I have determined whether this bug is also reproducible in a vanilla SwiftUI project.
      required: false
    - label: If possible, I've reproduced the issue using the `main` branch of this package.
      required: false
    - label: This issue hasn't been addressed in an [existing GitHub issue](https://github.com/klaviyo/klaviyo-swift-sdk/issues) or [discussion](https://github.com/pointfreeco/klaviyo/klaviyo-swift-sdk/discussions).
      required: true
- type: textarea
  attributes:
    label: Description
    description: |
      A short description of the incorrect behavior.

      If you think this issue has been recently introduced and did not occur in an earlier version, please note that.
      If possible, include the last version that the behavior was correct in addition to your current version.
  validations:
    required: true
- type: textarea
  attributes:
    label: Expected behavior
    description: Describe what you expected to happen.
  validations:
    required: true
- type: textarea
  attributes:
    label: Actual behavior
    description: Describe or copy/paste the behavior you observe.
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce
    description: |
      Explanation of how to reproduce the incorrect behavior.

      This could include an attached project or link to code that is exhibiting the issue, and/or a screen recording.
    placeholder: |
      1. ...
  validations:
    required: true
- type: input
  attributes:
    label: The Klaviyo Swift SDK version information
    description: The version of the Klaviyo Swift SDK used to reproduce this issue.
    placeholder: "'1.7.2' for example, or a commit hash"
  validations:
    required: true
- type: input
  attributes:
    label: Destination operating system
    description: The OS running your application.
    placeholder: "'iOS 15' for example"
  validations:
    required: true
- type: input
  attributes:
    label: Xcode version information
    description: The version of Xcode used to reproduce this issue.
    placeholder: "The version displayed from 'Xcode 〉About Xcode'"
  validations:
    required: true
- type: textarea
  attributes:
    label: Swift Compiler version information
    description: The version of Swift used to reproduce this issue.
    placeholder: Output from 'xcrun swiftc --version'
    render: shell
