platform :ios, '13.0'
use_frameworks!

target 'CocoapodsExample' do
  pod 'KlaviyoSwift', '5.5.0'
  pod 'KlaviyoForms', '5.5.0'
  pod 'KlaviyoLocation', '5.5.0'
end

target 'NotificationServiceExtension' do
  pod 'KlaviyoSwiftExtension', '5.5.0'
end
