platform :ios, '13.0'
use_frameworks!

target 'CocoapodsExample' do
  pod 'KlaviyoSwift', '5.2.1'
  pod 'KlaviyoForms', '5.2.1'
  pod 'KlaviyoLocation', '5.2.1'
end

target 'NotificationServiceExtension' do
  pod 'KlaviyoSwiftExtension', '5.2.1'
end
