platform :ios, '13.0'
use_frameworks!

target 'CocoapodsExample' do
  pod 'KlaviyoSwift', :git => 'https://github.com/klaviyo/klaviyo-swift-sdk.git', :branch => 'master'
end

target 'NotificationServiceExtension' do
    pod 'KlaviyoSwiftExtension', :git => 'https://github.com/klaviyo/klaviyo-swift-sdk.git', :branch => 'master'
end
